# Makefile for native tools
CFLAGS += -Wall -W

ifeq ($(OS),Windows_NT)
CC=x86_64-w64-mingw32-gcc 
RM=del
endif

##

all :: mkfloppy$X
clean :: ; $(RM) mkfloppy$X

##

all :: hex$X
clean :: ; $(RM) hex$X

##

all :: fat$X
clean :: ; $(RM) fat$X
